.. code-block:: yaml

    - name: Create a systemd-networkd interfaces
      hosts: localhost
      become: true
      roles:
        - role: "systemd_networkd"
          systemd_netdevs:
            - NetDev:
                Name: dummy0
                Kind: dummy
            - NetDev:
                Name: dummy1
                Kind: dummy
            - NetDev:
                Name: bond0
                Kind: bond
              Bond:
                Mode: 802.3ad
                TransmitHashPolicy: layer3+4
                MIIMonitorSec: 1s
                LACPTransmitRate: fast
            - NetDev:
                Name: br-dummy
                Kind: bridge
          systemd_networks:
            - interface: "dummy0"
              bond: "bond0"
              mtu: 9000
            - interface: "dummy1"
              bond: "bond0"
              mtu: 9000
            - interface: "bond0"
              bridge: "br-dummy"
              mtu: 9000
            - interface: "br-dummy"
              address: "10.0.0.100"
              netmask: "255.255.255.0"
              gateway: "10.0.0.1"
              mtu: 9000
              usedns: true
              config_overrides:
                Network:
                  ConfigureWithoutCarrier: true
